steps:
- name: node:14.15
  entrypoint: yarn
  args: ['install']
# - name: node
#   entrypoint: yarn
#   args: ['test']
- name: node:14.15.5
  entrypoint: yarn
  args: ['build']
- name: gcr.io/$PROJECT_ID/firebase
  args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']